using OKX.Api.Account.Enums;

namespace OKX.Api.Account.Converters;

internal class OkxAccountBillSubTypeConverter : BaseConverter<OkxAccountBillSubType>
{
    public OkxAccountBillSubTypeConverter() : this(true) { }
    public OkxAccountBillSubTypeConverter(bool quotes) : base(quotes) { }

    protected override List<KeyValuePair<OkxAccountBillSubType, string>> Mapping =>
    [
        new(OkxAccountBillSubType.Buy, "1"),
        new(OkxAccountBillSubType.Sell, "2"),
        new(OkxAccountBillSubType.OpenLong, "3"),
        new(OkxAccountBillSubType.OpenShort, "4"),
        new(OkxAccountBillSubType.CloseLong, "5"),
        new(OkxAccountBillSubType.CloseShort, "6"),
        new(OkxAccountBillSubType.InterestDeduction, "9"),
        new(OkxAccountBillSubType.TransferIn, "11"),
        new(OkxAccountBillSubType.TransferOut, "12"),
        new(OkxAccountBillSubType.InterestDeductionForVipLoans, "14"),
        new(OkxAccountBillSubType.RepayForcibly , "16"),
        new(OkxAccountBillSubType.RepayInterestByBorrowingForcibly , "17"),
        new(OkxAccountBillSubType.PartialLiquidationCloseLong, "100"),
        new(OkxAccountBillSubType.PartialLiquidationCloseShort, "101"),
        new(OkxAccountBillSubType.PartialLiquidationBuy, "102"),
        new(OkxAccountBillSubType.PartialLiquidationSell, "103"),
        new(OkxAccountBillSubType.LiquidationLong, "104"),
        new(OkxAccountBillSubType.LiquidationShort, "105"),
        new(OkxAccountBillSubType.LiquidationBuy, "106"),
        new(OkxAccountBillSubType.LiquidationSell, "107"),
        new(OkxAccountBillSubType.Clawback, "108"),
        new(OkxAccountBillSubType.LiquidationTransferIn, "110"),
        new(OkxAccountBillSubType.LiquidationTransferOut, "111"),
        new(OkxAccountBillSubType.DeliveryLong, "112"),
        new(OkxAccountBillSubType.DeliveryShort, "113"),
        new(OkxAccountBillSubType.AutoBuy, "114"),
        new(OkxAccountBillSubType.AutoSell, "115"),
        new(OkxAccountBillSubType.DeliveryExerciseClawback, "117"),
        new(OkxAccountBillSubType.SystemTokenConversionTransferIn, "118"),
        new(OkxAccountBillSubType.SystemTokenConversionTransferOut, "119"),
        new(OkxAccountBillSubType.ADLCloseLong, "125"),
        new(OkxAccountBillSubType.ADLCloseShort, "126"),
        new(OkxAccountBillSubType.ADLBuy, "127"),
        new(OkxAccountBillSubType.ADLSell, "128"),
        new(OkxAccountBillSubType.DDHBuy, "131"),
        new(OkxAccountBillSubType.DDHSell, "132"),
        new(OkxAccountBillSubType.ManualMarginIncrease, "160"),
        new(OkxAccountBillSubType.ManualMarginDecrease, "161"),
        new(OkxAccountBillSubType.AutoMarginIncrease, "162"),
        new(OkxAccountBillSubType.Exercised, "170"),
        new(OkxAccountBillSubType.CounterpartyExercised, "171"),
        new(OkxAccountBillSubType.ExpiredOTM, "172"),
        new(OkxAccountBillSubType.FundingFeeExpense, "173"),
        new(OkxAccountBillSubType.FundingFeeIncome, "174"),
        new(OkxAccountBillSubType.SystemTransferIn, "200"),
        new(OkxAccountBillSubType.ManuallyTransferIn, "201"),
        new(OkxAccountBillSubType.SystemTransferOut, "202"),
        new(OkxAccountBillSubType.ManuallyTransferOut, "203"),
        new(OkxAccountBillSubType.BlockTradeBuy, "204"),
        new(OkxAccountBillSubType.BlockTradeSell, "205"),
        new(OkxAccountBillSubType.BlockTradeOpenLong, "206"),
        new(OkxAccountBillSubType.BlockTradeOpenShort, "207"),
        new(OkxAccountBillSubType.BlockTradeCloseOpen, "208"),
        new(OkxAccountBillSubType.BlockTradeCloseShort, "209"),
        new(OkxAccountBillSubType.ManualBorrowing, "210"),
        new(OkxAccountBillSubType.ManualRepayment, "211"),
        new(OkxAccountBillSubType.AutoBorrow, "212"),
        new(OkxAccountBillSubType.AutoRepay, "213"),
        new(OkxAccountBillSubType.RepaymentTransferIn, "224"),
        new(OkxAccountBillSubType.RepaymentTransferOut, "225"),
        new(OkxAccountBillSubType.ProfitSharingExpenses, "250"),
        new(OkxAccountBillSubType.ProfitSharingRefund, "251"),
        new(OkxAccountBillSubType.ProfitSharingIncome, "252"),
        new(OkxAccountBillSubType.SpreadTradingBuy, "270"),
        new(OkxAccountBillSubType.SpreadTradingSell, "271"),
        new(OkxAccountBillSubType.SpreadTradingOpenLong, "272"),
        new(OkxAccountBillSubType.SpreadTradingOpenShort, "273"),
        new(OkxAccountBillSubType.SpreadTradingCloseLong, "274"),
        new(OkxAccountBillSubType.SpreadTradingCloseShort, "275"),
        new(OkxAccountBillSubType.SpotProfitSharingExpenses, "280"),
        new(OkxAccountBillSubType.SpotProfitSharingRefund, "281"),
    ];
}