using OKX.Api.Account.Enums;

namespace OKX.Api.Account.Converters;

internal class OkxBillSubTypeConverter : BaseConverter<OkxBillSubType>
{
    public OkxBillSubTypeConverter() : this(true) { }
    public OkxBillSubTypeConverter(bool quotes) : base(quotes) { }

    protected override List<KeyValuePair<OkxBillSubType, string>> Mapping =>
    [
        new(OkxBillSubType.Buy, "1"),
        new(OkxBillSubType.Sell, "2"),
        new(OkxBillSubType.OpenLong, "3"),
        new(OkxBillSubType.OpenShort, "4"),
        new(OkxBillSubType.CloseLong, "5"),
        new(OkxBillSubType.CloseShort, "6"),
        new(OkxBillSubType.InterestDeduction, "9"),
        new(OkxBillSubType.TransferIn, "11"),
        new(OkxBillSubType.TransferOut, "12"),
        new(OkxBillSubType.InterestDeductionForVipLoans, "14"),
        new(OkxBillSubType.RepayForcibly , "16"),
        new(OkxBillSubType.RepayInterestByBorrowingForcibly , "17"),
        new(OkxBillSubType.PartialLiquidationCloseLong, "100"),
        new(OkxBillSubType.PartialLiquidationCloseShort, "101"),
        new(OkxBillSubType.PartialLiquidationBuy, "102"),
        new(OkxBillSubType.PartialLiquidationSell, "103"),
        new(OkxBillSubType.LiquidationLong, "104"),
        new(OkxBillSubType.LiquidationShort, "105"),
        new(OkxBillSubType.LiquidationBuy, "106"),
        new(OkxBillSubType.LiquidationSell, "107"),
        new(OkxBillSubType.Clawback, "108"),
        new(OkxBillSubType.LiquidationTransferIn, "110"),
        new(OkxBillSubType.LiquidationTransferOut, "111"),
        new(OkxBillSubType.DeliveryLong, "112"),
        new(OkxBillSubType.DeliveryShort, "113"),
        new(OkxBillSubType.AutoBuy, "114"),
        new(OkxBillSubType.AutoSell, "115"),
        new(OkxBillSubType.DeliveryExerciseClawback, "117"),
        new(OkxBillSubType.SystemTokenConversionTransferIn, "118"),
        new(OkxBillSubType.SystemTokenConversionTransferOut, "119"),
        new(OkxBillSubType.ADLCloseLong, "125"),
        new(OkxBillSubType.ADLCloseShort, "126"),
        new(OkxBillSubType.ADLBuy, "127"),
        new(OkxBillSubType.ADLSell, "128"),
        new(OkxBillSubType.DDHBuy, "131"),
        new(OkxBillSubType.DDHSell, "132"),
        new(OkxBillSubType.ManualMarginIncrease, "160"),
        new(OkxBillSubType.ManualMarginDecrease, "161"),
        new(OkxBillSubType.AutoMarginIncrease, "162"),
        new(OkxBillSubType.Exercised, "170"),
        new(OkxBillSubType.CounterpartyExercised, "171"),
        new(OkxBillSubType.ExpiredOTM, "172"),
        new(OkxBillSubType.FundingFeeExpense, "173"),
        new(OkxBillSubType.FundingFeeIncome, "174"),
        new(OkxBillSubType.SystemTransferIn, "200"),
        new(OkxBillSubType.ManuallyTransferIn, "201"),
        new(OkxBillSubType.SystemTransferOut, "202"),
        new(OkxBillSubType.ManuallyTransferOut, "203"),
        new(OkxBillSubType.BlockTradeBuy, "204"),
        new(OkxBillSubType.BlockTradeSell, "205"),
        new(OkxBillSubType.BlockTradeOpenLong, "206"),
        new(OkxBillSubType.BlockTradeOpenShort, "207"),
        new(OkxBillSubType.BlockTradeCloseOpen, "208"),
        new(OkxBillSubType.BlockTradeCloseShort, "209"),
        new(OkxBillSubType.ManualBorrowing, "210"),
        new(OkxBillSubType.ManualRepayment, "211"),
        new(OkxBillSubType.AutoBorrow, "212"),
        new(OkxBillSubType.AutoRepay, "213"),
        new(OkxBillSubType.RepaymentTransferIn, "224"),
        new(OkxBillSubType.RepaymentTransferOut, "225"),
        new(OkxBillSubType.ProfitSharingExpenses, "250"),
        new(OkxBillSubType.ProfitSharingRefund, "251"),
        new(OkxBillSubType.ProfitSharingIncome, "252"),
        new(OkxBillSubType.SpreadTradingBuy, "270"),
        new(OkxBillSubType.SpreadTradingSell, "271"),
        new(OkxBillSubType.SpreadTradingOpenLong, "272"),
        new(OkxBillSubType.SpreadTradingOpenShort, "273"),
        new(OkxBillSubType.SpreadTradingCloseLong, "274"),
        new(OkxBillSubType.SpreadTradingCloseShort, "275"),
        new(OkxBillSubType.SpotProfitSharingExpenses, "280"),
        new(OkxBillSubType.SpotProfitSharingRefund, "281"),
    ];
}