using System;

namespace OKX.Api.Converters;

internal class AccountBillSubTypeConverter : BaseConverter<OkxAccountBillSubType>
{
    public AccountBillSubTypeConverter() : this(true) { }
    public AccountBillSubTypeConverter(bool quotes) : base(quotes) { }

    protected override List<KeyValuePair<OkxAccountBillSubType, string>> Mapping => new()
    {
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.Buy, "1"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.Sell, "2"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.OpenLong, "3"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.OpenShort, "4"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.CloseLong, "5"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.CloseShort, "6"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.InterestDeduction, "9"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.TransferIn, "11"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.TransferOut, "12"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.InterestDeductionForVipLoans, "14"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.RepayForcibly , "16"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.RepayInterestByBorrowingForcibly , "17"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.PartialLiquidationCloseLong, "100"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.PartialLiquidationCloseShort, "101"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.PartialLiquidationBuy, "102"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.PartialLiquidationSell, "103"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.LiquidationLong, "104"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.LiquidationShort, "105"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.LiquidationBuy, "106"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.LiquidationSell, "107"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.Clawback, "108"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.LiquidationTransferIn, "110"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.LiquidationTransferOut, "111"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.DeliveryLong, "112"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.DeliveryShort, "113"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.AutoBuy, "114"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.AutoSell, "115"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.DeliveryExerciseClawback, "117"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SystemTokenConversionTransferIn, "118"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SystemTokenConversionTransferOut, "119"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ADLCloseLong, "125"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ADLCloseShort, "126"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ADLBuy, "127"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ADLSell, "128"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.DDHBuy, "131"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.DDHSell, "132"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ManualMarginIncrease, "160"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ManualMarginDecrease, "161"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.AutoMarginIncrease, "162"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.Exercised, "170"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.CounterpartyExercised, "171"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ExpiredOTM, "172"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.FundingFeeExpense, "173"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.FundingFeeIncome, "174"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SystemTransferIn, "200"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ManuallyTransferIn, "201"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SystemTransferOut, "202"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ManuallyTransferOut, "203"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.BlockTradeBuy, "204"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.BlockTradeSell, "205"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.BlockTradeOpenLong, "206"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.BlockTradeOpenShort, "207"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.BlockTradeCloseOpen, "208"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.BlockTradeCloseShort, "209"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ManualBorrowing, "210"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ManualRepayment, "211"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.AutoBorrow, "212"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.AutoRepay, "213"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.RepaymentTransferIn, "224"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.RepaymentTransferOut, "225"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ProfitSharingExpenses, "250"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ProfitSharingRefund, "251"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.ProfitSharingIncome, "252"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SpreadTradingBuy, "270"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SpreadTradingSell, "271"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SpreadTradingOpenLong, "272"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SpreadTradingOpenShort, "273"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SpreadTradingCloseLong, "274"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SpreadTradingCloseShort, "275"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SpotProfitSharingExpenses, "280"),
            new KeyValuePair<OkxAccountBillSubType, string>(OkxAccountBillSubType.SpotProfitSharingRefund, "281"),

        };
}